// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rotdapktuwxwvylhnfry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvdGRhcGt0dXd4d3Z5bGhuZnJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzQ2MDUsImV4cCI6MjA2ODQ1MDYwNX0.4x6ITNkua54sQrJ5urv8_cAGPtPF8WtBzBH7AVJ1rQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});